### ISSUE TITLE
Any plans to port this to .net core?

### ISSUE THREAD

**Issue by Cephei** [dxFeed/dxfeed-net-api#22]

**Comment by ttldtor** [comment]
Hello, @Cephei 

We plan to support multiple versions. We'll also take into account the release of .Net 5.0 (~2020-11).
I think we will start working on this in December-January.

**Comment by Cyral** [comment]
+1

I am currently using a TCP server and the Java API to send quotes from Java to C# (.NET Core), but there is extra overhead and it is not the best solution. It would be great to have a .NET Core library.

**Comment by Cyral** [comment]
@ttldtor Any update on the timeline for this?

**Comment by IsaackRasmussen** [comment]
Any updates?
