### ISSUE TITLE
Where to pass the token?

### ISSUE THREAD

**Issue by gowthamnatarajan** [dxFeed/dxfeed-net-api#61]
How do I pass the token to get live data? There is no parameter to pass a token. My websoket URL is for live data.

In python it's as follows:

```
const feed = new Feed()
feed.setAuthToken('Token')
```

Overall I am trying to write the following python code in C#

```
import Feed, { EventType } from '@dxfeed/api'
const feed = new Feed()
feed.setAuthToken('Token')
feed.connect('https://tasty-live-web.dxfeed.com/live/cometd')

feed.subscribe(
  [EventType.Greeks, EventType.Profile, EventType.Quote, EventType.Summary, EventType.Trade],
  ['AAPL', '.AAPL220617P150'],
  event => console.log(event)
)
```

**Comment by Strotsev** [comment]
Hello, @gowthamnatarajan !
Here is [the link](https://docs.dxfeed.com/net-api/classcom_1_1dxfeed_1_1native_1_1NativeConnection.html#aeca3df7b406db9bb3bd0c10e69053b62) to the documentation.
And here is [the link](https://github.com/dxFeed/dxfeed-net-api/blob/master/samples/dxf_events_sample/Program.cs#L114) to an example where this method is used.
If you still have questions or new ones appear, you can also ask them on [our portal](https://jira.in.devexperts.com/servicedesk/customer/portal/1).
